# Generated by Django 5.1.3 on 2024-11-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video1', models.FileField(upload_to='videos/')),
                ('video2', models.FileField(upload_to='videos/')),
                ('video1_name', models.CharField(blank=True, max_length=255)),
                ('video2_name', models.CharField(blank=True, max_length=255)),
                ('audio_offset', models.FloatField(blank=True, null=True)),
                ('standard_score', models.FloatField(blank=True, null=True)),
                ('match_found', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
